name: Run Next.js App in Dev Mode

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      environment:
        description: 'Environment to deploy (e.g., development or production)'
        required: false
        default: 'development'

jobs:
  run-nextjs:
    runs-on: self-hosted

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Build and run Docker container
      - name: Run Docker Container
        run: |
          docker build -t nextjs-app .
          docker run -d -p 3030:3030 --name nextjs-container nextjs-app
