name: Build and Serve Next.js App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      environment:
        description: 'Environment to deploy (e.g., development or production)'
        required: false
        default: 'development'

jobs:
  build-and-serve:
    runs-on: self-hosted

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version

      # Install dependencies
      - name: Install Dependencies
        run: |
          npm install

      # Run the development server on port 1234
      - name: Run Development Server
        run: |
          npm run dev
      # Optionally, verify the app is running
      - name: Test Application is Running
        run: |
          curl -I http://localhost:3030
