name: Run Next.js App in Dev Mode

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      environment:
        description: 'Environment to deploy (e.g., development or production)'
        required: false
        default: 'development'

jobs:
  run-nextjs:
    runs-on: self-hosted

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Cleanup existing Docker container if it exists
      - name: Cleanup Existing Container
        run: |
          if [ "$(docker ps -aq -f name=moniplant-frontend)" ]; then
            echo "Stopping and removing existing container..."
            docker stop moniplant-frontend || true
            docker rm moniplant-frontend || true
          else
            echo "No existing container to cleanup."
          fi

      # Build and run Docker container
      - name: Run Docker Container
        run: |
          docker build -t nextjs-app .
          docker run -d -p 3030:3030 --name moniplant-frontend --network gateway-microservice_localnet nextjs-app
